from vector_fsm import *

class SimpleMotion(StateMachineProgram):
    def setup(self):
        """
            Forward(50)=C=>Turn(30)=C=>Say("Save Anki!")
        """
        
        # Code generated by genfsm on Tue Apr 30 14:01:24 2019:
        
        forward1 = Forward(50) .set_name("forward1") .set_parent(self)
        turn1 = Turn(30) .set_name("turn1") .set_parent(self)
        say1 = Say("Save Anki!") .set_name("say1") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(forward1) .add_destinations(turn1)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(turn1) .add_destinations(say1)
        
        return self
